//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STALK_IRC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STALK_IRC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;window&gt;
        ///	&lt;edit_box x=&quot;20&quot; y=&quot;718&quot; width=&quot;984&quot; height=&quot;30&quot;&gt;
        ///		&lt;texture&gt;ui_linetext_e&lt;/texture&gt;
        ///		&lt;text x=&quot;10&quot; font=&quot;letterica18&quot; r=&quot;240&quot; g=&quot;217&quot; b=&quot;182&quot;/&gt;
        ///	&lt;/edit_box&gt;
        ///	
        ///	&lt;button_send x=&quot;750&quot; y=&quot;668&quot; width=&quot;117&quot; height=&quot;29&quot;&gt;
        ///		&lt;texture&gt;ui_button_ordinary&lt;/texture&gt;
        ///		&lt;text font=&quot;letterica18&quot; align=&quot;c&quot;&gt;Send&lt;/text&gt;
        ///		&lt;text_color&gt;
        ///			&lt;e r=&quot;227&quot; g=&quot;199&quot; b=&quot;178&quot;/&gt;
        ///			&lt;t r=&quot;180&quot; g=&quot;153&quot; b=&quot;155&quot;/&gt;
        ///			&lt;d r=&quot;106&quot; g=&quot; 95&quot; b=&quot; 91&quot;/&gt;
        ///			&lt;h r=&quot;  0&quot; g=&quot;  0&quot; b=&quot;  0&quot;/&gt;
        ///		&lt;/text_color&gt;
        ///	&lt;/button_send&gt;
        ///	
        ///	&lt;bu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chatInputUIXML {
            get {
                return ResourceManager.GetString("chatInputUIXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function init    (obj)
        ///				xr_motivator.AddToMotivator(obj)
        ///end
        ///
        ///function actor_init    (npc)
        ///				npc:bind_object(actor_binder(npc))
        ///end
        ///
        ///local game_difficulty_by_num = {
        ///				[0] = &quot;gd_novice&quot;,
        ///				[1] = &quot;gd_stalker&quot;,
        ///				[2] = &quot;gd_veteran&quot;,
        ///				[3] = &quot;gd_master&quot;
        ///				}
        ///
        ///local weapon_hide = {}
        ///local primary_objects_filled = false
        ///----------------------------------------------------------------------------------------------------------------------
        ///class &quot;actor_binder&quot; (object_binder)
        ///------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string copBindStalker {
            get {
                return ResourceManager.GetString("copBindStalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- File:        UI_MAIN_MENU.SCRIPT
        ///-- Description: Load Dialog for STALKER
        ///-- Created:     28.10.2004
        ///-- Lasd edit:	18.01.2006
        ///-- Copyright:   2004 GSC Game World
        ///-- Author:      Serhiy Vynnychenko (narrator@gsc-game.kiev.ua)
        ///-- Version:     0.9
        ///
        ///class &quot;main_menu&quot; (CUIScriptWnd)
        ///
        ///function main_menu:__init() super()
        ///	self.mbox_mode = 0
        ///    self:InitControls()
        ///    self:InitCallBacks()
        ///    xr_s.on_main_menu_on()     						 --&apos; Distemper 03.2008 --
        ///end
        ///
        ///function main_menu:__finalize()
        ///end
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string copMainMenu {
            get {
                return ResourceManager.GetString("copMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function init    (obj)
        ///				xr_motivator.AddToMotivator(obj)
        ///end
        ///
        ///function actor_init    (npc)
        ///				npc:bind_object(actor_binder(npc))
        ///end
        ///
        ///delayed_alife_release_objects = {}
        ///to_delayed_alife_release_objects = {}
        ///
        ///local game_difficulty_by_num = {
        ///				[0] = &quot;gd_novice&quot;,
        ///				[1] = &quot;gd_stalker&quot;,
        ///				[2] = &quot;gd_veteran&quot;,
        ///				[3] = &quot;gd_master&quot;
        ///				}
        ///
        ///lasthealth  = 0
        ///lasttime        = 0
        ///post_process = 0
        ///local weapon_hide = {}
        ///--------------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csBindStalker {
            get {
                return ResourceManager.GetString("csBindStalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- File:        UI_MAIN_MENU.SCRIPT
        ///-- Description: Load Dialog for STALKER
        ///-- Created:     28.10.2004
        ///-- Lasd edit:	18.01.2006
        ///-- Copyright:   2004 GSC Game World
        ///-- Author:      Serhiy Vynnychenko (narrator@gsc-game.kiev.ua)
        ///-- Version:     0.9
        ///
        ///class &quot;main_menu&quot; (CUIScriptWnd)
        ///
        ///function main_menu:__init() super()
        ///	self.mbox_mode = 0
        ///    self:InitControls()
        ///    self:InitCallBacks()
        ///    xr_s.on_main_menu_on()     						 --&apos; Distemper 03.2008 --
        ///end
        ///
        ///function main_menu:__finalize()
        ///end
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csMainMenu {
            get {
                return ResourceManager.GetString("csMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --[[ ----------------------------------------------------------------------------------------------
        /// File       : bind_actor.script
        /// Description: Actor Binder
        /// Copyright  : 2004 © GSC Game World
        /// Author     : Game World &amp; LA-team
        /// Editors    : barin, gr1ph00n, SkyLoader, vintar
        /// Last edit  : 15.04.2013 [vintar]
        ///--]] ----------------------------------------------------------------------------------------------
        ///
        ///--/ -----------------------------------------------------------------
        ///--/ VARIABLEs
        ///--/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string laBindActor {
            get {
                return ResourceManager.GetString("laBindActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --[[-----------------------------------------------------------------------------------------------
        /// File       : ui_main_menu.script
        /// Description: Main Menu Dialog for STALKER
        /// Copyright  : 2004 © GSC Game World
        /// Author     : Serhiy Vynnychenko (narrator@gsc-game.kiev.ua)
        /// Editors    : barin (22.08.2010)
        /// Last edit  : 05.04.2013 [...]
        ///--]]-----------------------------------------------------------------------------------------------
        ///
        ///--/ ------------------------------------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string laMainMenu {
            get {
                return ResourceManager.GetString("laMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function init    (obj)
        ///	xr_motivator.AddToMotivator(obj)
        ///end
        ///
        ///function actor_init    (npc)
        ///	npc:bind_object(actor_binder(npc))
        ///end
        ///
        ///local game_difficulty_by_num = {
        ///	[0] = &quot;gd_novice&quot;,
        ///	[1] = &quot;gd_stalker&quot;,
        ///	[2] = &quot;gd_veteran&quot;,
        ///	[3] = &quot;gd_master&quot;
        ///	}
        ///
        ///lasthealth  = 0
        ///lasttime	= 0
        ///post_process = 0
        ///local weapon_hide = false
        ///----------------------------------------------------------------------------------------------------------------------
        ///class &quot;actor_binder&quot; (object_binder)
        ///------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string socBindStalker {
            get {
                return ResourceManager.GetString("socBindStalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [messages]
        ///.
        /// </summary>
        internal static string socInputClear {
            get {
                return ResourceManager.GetString("socInputClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- File:        UI_MAIN_MENU.SCRIPT
        ///-- Description: Load Dialog for STALKER
        ///-- Created:     28.10.2004
        ///-- Lasd edit:	18.01.2006
        ///-- Copyright:   2004 GSC Game World
        ///-- Author:      Serhiy Vynnychenko (narrator@gsc-game.kiev.ua)
        ///-- Version:     0.9
        ///
        ///class &quot;main_menu&quot; (CUIScriptWnd)
        ///
        ///function main_menu:__init() super()
        ///	self.mbox_mode = 0
        ///   self:InitControls()
        ///   self:InitCallBacks()
        ///end
        ///
        ///function main_menu:__finalize()
        ///
        ///end
        ///
        ///function main_menu:InitControls()
        ///	self:Init(0,0,1024,768)			   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string socMainMenu {
            get {
                return ResourceManager.GetString("socMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] stalkIRCIcons {
            get {
                object obj = ResourceManager.GetObject("stalkIRCIcons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- List of texture coordinates/IDs for STALK-IRC icons
        ///-- Moved to a separate script because it&apos;s xbox hueg
        ///
        ///if stalk_irc.game == &quot;SoC&quot; or stalk_irc.game == &quot;LA&quot; then
        ///	info = Frect():set( 5053, 935, 163, 85 )
        ///	tkgp = {
        ///		SOC	= Frect():set( 5053, 0, 163, 85 ),
        ///		CS	= Frect():set( 5053, 85, 163, 85 ),
        ///		COP	= Frect():set( 5053, 170, 163, 85 ),
        ///		LA	= Frect():set( 5053, 255, 163, 85 )
        ///		}
        ///	Loners = {
        ///		{	SOC	= Frect():set( 0, 0, 163, 85 ),
        ///			CS	= Frect():set( 0, 85, 163, 85 ),
        ///			COP	= Frect():s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stalkIRCIconsScript {
            get {
                return ResourceManager.GetString("stalkIRCIconsScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w&gt;
        ///    &lt;file name=&quot;ui\stalk_irc_icons&quot;&gt;
        ///		&lt;texture id=&quot;si_icon_info&quot; x=&quot;5053&quot; y=&quot;935&quot; width=&quot;163&quot; height=&quot;85&quot; /&gt;
        ///		&lt;texture id=&quot;si_icon_tkgp_soc&quot; x=&quot;5053&quot; y=&quot;0&quot; width=&quot;163&quot; height=&quot;85&quot; /&gt;
        ///		&lt;texture id=&quot;si_icon_tkgp_cs&quot; x=&quot;5053&quot; y=&quot;85&quot; width=&quot;163&quot; height=&quot;85&quot; /&gt;
        ///		&lt;texture id=&quot;si_icon_tkgp_cop&quot; x=&quot;5053&quot; y=&quot;170&quot; width=&quot;163&quot; height=&quot;85&quot; /&gt;
        ///		&lt;texture id=&quot;si_icon_tkgp_la&quot; x=&quot;5053&quot; y=&quot;255&quot; width=&quot;163&quot; height=&quot;85&quot; /&gt;
        ///		
        ///		&lt;texture id=&quot;si_icon_loner1_soc&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;163&quot; height=&quot;85&quot; /&gt;
        ///		&lt;textur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stalkIRCIconsXML {
            get {
                return ResourceManager.GetString("stalkIRCIconsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --| Game interface for STALK-IRC
        ///--| Last modified: Mar 6, &apos;15
        ///--| By: TKGP
        ///
=======
        ///   Looks up a localized string similar to --| Game interface for STALK-IRC
        ///--| Last modified: Feb 26, &apos;15
        ///--| By: TKGP
        ///
        ///local CHATKEY			= DIK_keys.DIK_APOSTROPHE	-- Key to trigger chat box UI
>>>>>>> origin/master
        ///local UPDATEINTERVAL	= 1000						-- Time between file checks in milliseconds
        ///local INPATH			= getFS():update_path( &quot;$fs_root$&quot;, &quot;&quot; )..&quot;\\STALK-IRC_input.txt&quot;
        ///local OUTPATH			= getFS():update_path( &quot;$fs_root$&quot;, &quot;&quot; )..&quot;\\STALK-IRC_output.txt&quot;
        ///local INPUTREGEX		= &quot;([^/]+)/([^/]+)/(.+)&quot;	-- Regular expression for parsing input
<<<<<<< HEAD
        ///local ssVer				= script_server_object_version()
        ///game					= ( ssVer &gt;= 12 and &quot;CoP&quot; ) or ( ssVer &gt;= 8 a [rest of string was truncated]&quot;;.
=======
        ///local ssVer				= script_serve [rest of string was truncated]&quot;;.
>>>>>>> origin/master
        /// </summary>
        internal static string stalkIRCScript {
            get {
                return ResourceManager.GetString("stalkIRCScript", resourceCulture);
            }
        }
    }
}
